In [29]:
from sklearn.preprocessing import StandardScaler
import numpy as np
import os 
import pandas as pd 
import pandas as pd
import matplotlib.pyplot as plt
import cv2
from skimage.feature import hog
import pickle

In [30]:
if not os.path.exists('/home/rupok1/Downloads/Normal'):
    print('The directory /Desktop/Normal does not exist.')
elif not os.listdir('/home/rupok1/Downloads/Normal'):
    print('The directory /Desktop/Normal is empty.')
else:
    for dirname, _, filenames in os.walk('/home/rupok1/Downloads/Normal'):
        for filename in filenames:
            print(os.path.join(dirname, filename))


if not os.path.exists('/home/rupok1/Downloads/Sick'):
    print('The directory /Desktop/Sick does not exist.')
elif not os.listdir('/home/rupok1/Downloads/Normal'):
    print('The directory /Desktop/Sick is empty.')
else:
    for dirname, _, filenames in os.walk('/home/rupok1/Downloads/Sick'):
        for filename in filenames:
            print(os.path.join(dirname, filename))

/home/rupok1/Downloads/Normal/img0003--57.524.jpg
/home/rupok1/Downloads/Normal/img0009-38.jpg
/home/rupok1/Downloads/Normal/img0021--150.487.jpg
/home/rupok1/Downloads/Normal/img0032--26.9148.jpg
/home/rupok1/Downloads/Normal/img0029--26.9148.jpg
/home/rupok1/Downloads/Normal/img0001-52.1049.jpg
/home/rupok1/Downloads/Normal/img0001-50.9869.jpg
/home/rupok1/Downloads/Normal/img0016--26.9148.jpg
/home/rupok1/Downloads/Normal/img0007-38.jpg
/home/rupok1/Downloads/Normal/img0017-91.436.jpg
/home/rupok1/Downloads/Normal/img0001--3.94394.jpg
/home/rupok1/Downloads/Normal/img0002--68.164.jpg
/home/rupok1/Downloads/Normal/img0001-47.8247.jpg
/home/rupok1/Downloads/Normal/img0005--26.9148.jpg
/home/rupok1/Downloads/Normal/img0032--18.4867.jpg
/home/rupok1/Downloads/Normal/img0015-38.jpg
/home/rupok1/Downloads/Normal/img0012-38.236.jpg
/home/rupok1/Downloads/Normal/img0030-50.9869.jpg
/home/rupok1/Downloads/Normal/img0013-48.876.jpg
/home/rupok1/Downloads/Normal/img0018--26.9148.jpg
/home/rupo

In [31]:
normal_path = '/home/rupok1/Downloads/Normal'
sick_path = '/home/rupok1/Downloads/Sick'

In [32]:
normal_images = []
for image_file in os.listdir(normal_path):
    image_path = os.path.join(normal_path, image_file)
    image = cv2.imread(image_path)
    
    if image is not None:
        normal_images.append(image)

In [33]:
normal_images

[array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 array([[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]

In [34]:
sick_images = []
for image_file in os.listdir(sick_path):
    image_path = os.path.join(sick_path, image_file)
    image = cv2.imread(image_path)
    
    if image is not None:
        sick_images.append(image)

In [35]:
sick_images

[array([[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        [[ 0,  0,  0],
         [ 2,  2,  2],
         [ 1,  1,  1],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        ...,
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [53, 53, 53],
         [53, 53, 53],
         [ 0,  0,  0]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [39, 39, 39],
         [39, 39, 39],
         [ 0,  0,  0]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]], dtype=uint8),
 array([[[ 0,  0,  0],
         [ 0,  0,  

In [36]:
def preprocess_image(image):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    image = cv2.resize(image, (224, 224))
    image = image / 255.0
    return image

In [37]:
preprocessed_normal_images = []
for image in normal_images:
    preprocessed_image = preprocess_image(image)
    preprocessed_normal_images.append(preprocessed_image)

In [38]:
preprocessed_normal_images

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.01960784, 0.21960784, 0.21568627, ..., 0.00392157, 0.        ,
         0.        ],
        [0.01960784, 0.23137255, 0.21568627, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.01568627, 0.19607843, 0.22352941, ..., 0.31764706, 0.3372549 ,
         0.03137255],
        [0.01568627, 0.19607843, 0.21960784, ..., 0.13333333, 0.02352941,
         0.00392157],
        [0.01960784, 0.20392157, 0.20392157, ..., 0.        , 0.        ,
         0.        ]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 

In [39]:
preprocessed_sick_images = []
for image in sick_images:
    preprocessed_image = preprocess_image(image)
    preprocessed_sick_images.append(preprocessed_image)

In [40]:
preprocessed_sick_images

[array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.14117647, 0.05098039,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.0745098 , 0.02745098,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]]),
 array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.00392157, 0.00392157, ..., 0.        , 0.        ,
         0.00392157],
        [0.        , 0.01176471, 0.00784314, ..., 0.00392157, 0.        ,
         0.        ],
        ...,
        [0.        , 0.19215686, 0.25098039, ..., 0.17647059, 0.14901961,
         0.        ],
        [0. 

In [43]:
def extract_hog_features(image):
    hog_features = hog(image, orientations=8, pixels_per_cell=(8, 8), cells_per_block=(2, 2))
    return hog_features

In [44]:
normal_hog_features = []
for image in preprocessed_normal_images:
    hog_features = extract_hog_features(image)
    normal_hog_features.append(hog_features)


In [45]:
normal_hog_features

[array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.2792312 , 0.0148812 , 0.16432925, ..., 0.01213684, 0.0787509 ,
        0.26474218]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.16926077,
        0.        ]),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.13188076,
        0.        ]),
 array([0.        , 0.        , 0.        , ..., 0.02075997, 0.07877853,
        0.        ]),
 array([0.105999  , 0.        , 0.07495261, ..., 0.        , 0.        ,
        0.        ]),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.05237135,
        0.        ]),
 array([0.25470399, 0.07955682, 0.11927164, ..., 0.05248855, 0.10696101,
        0.19067422]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.25818736, 0.16558208, 0.25818736, ..., 0.10331165, 0.08545505,
        0.15933847]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.05910294, 0.        , 0.        , ..., 0.07740357, 0.        ,
        0.1

In [46]:
sick_hog_features = []
for image in preprocessed_sick_images:
    hog_features = extract_hog_features(image)
    sick_hog_features.append(hog_features)

In [47]:
sick_hog_features

[array([0.29932784, 0.        , 0.29932784, ..., 0.05590326, 0.07765506,
        0.27321096]),
 array([0.11238556, 0.08218133, 0.07558957, ..., 0.00771637, 0.01127314,
        0.23592425]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.30899012, 0.        , 0.23652123, ..., 0.        , 0.        ,
        0.        ]),
 array([0.23641547, 0.        , 0.03039472, ..., 0.        , 0.        ,
        0.        ]),
 array([0.        , 0.19648103, 0.086465  , ..., 0.20822697, 0.23987006,
        0.        ]),
 array([0.133261  , 0.02037562, 0.01211722, ..., 0.        , 0.        ,
        0.        ]),
 array([0.26446665, 0.0985609 , 0.12467076, ..., 0.        , 0.        ,
        0.        ]),
 array([0.3049885 , 0.11939342, 0.25491791, ..., 0.01905404, 0.01850018,
        0.19289862]),
 array([0.17822807, 0.        , 0.08401752, ..., 0.        , 0.        ,
        0.        ]),
 array([0.22822391, 0.        , 0.22593013, ..., 0.05794147, 0.08173975,
        0.27192812]),
 array([0.0

In [48]:
all_hog_features = np.concatenate((normal_hog_features, sick_hog_features))

In [49]:
num_features = all_hog_features.shape[1]
column_names = ["feature_" + str(i) for i in range(num_features)]

hog_df = pd.DataFrame(all_hog_features, columns=column_names)

In [50]:
hog_df

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
1     0.279231   0.014881   0.164329   0.021535   0.279231   0.232855   
2     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
3     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
4     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
..         ...        ...        ...        ...        ...        ...   
127   0.214739   0.048017   0.182212   0.000000   0.276253   0.048017   
128   0.049520   0.028470   0.005267   0.041490   0.067098   0.035962   
129   0.270254   0.000000   0.049397   0.000000   0.244503   0.000000   
130   0.243791   0.000000   0.086193   0.000000   0.060948   0.000000   
131   0.262784   0.106837   0.268913   0.000000   0.262784   0.000000   

     feature_6  feature_7  feature_8  feature_9  ...  feature_23318  \
0     0.000000   0.000000   0.000000   0.000000  ...       0.000000   
1     0.116824   0.279231   0.135777   0.070126  ...       0.019847   
2     0.000000   0.000000   0.000000   0.000000  ...       0.000000   
3     0.000000   0.000000   0.000000   0.000000  ...       0.225681   
4     0.000000   0.000000   0.000000   0.000000  ...       0.299579   
..         ...        ...        ...        ...  ...            ...   
127   0.108754   0.000000   0.276253   0.192068  ...       0.140447   
128   0.012990   0.061640   0.176685   0.261134  ...       0.000000   
129   0.049397   0.000000   0.270254   0.000000  ...       0.087975   
130   0.000000   0.000000   0.243791   0.000000  ...       0.113810   
131   0.067570   0.000000   0.262784   0.000000  ...       0.029932   

     feature_23319  feature_23320  feature_23321  feature_23322  \
0         0.000000       0.000000       0.000000       0.000000   
1         0.193778       0.264742       0.145388       0.203703   
2         0.000000       0.000000       0.000000       0.000000   
3         0.000000       0.284688       0.000000       0.169261   
4         0.000000       0.299579       0.000000       0.299579   
..             ...            ...            ...            ...   
127       0.000000       0.099311       0.000000       0.070224   
128       0.000000       0.000000       0.000000       0.000000   
129       0.000000       0.322049       0.000000       0.263926   
130       0.000000       0.160952       0.000000       0.113810   
131       0.036762       0.262894       0.148428       0.127123   

     feature_23323  feature_23324  feature_23325  feature_23326  feature_23327  
0         0.000000       0.000000       0.000000       0.000000       0.000000  
1         0.264742       0.080699       0.012137       0.078751       0.264742  
2         0.000000       0.000000       0.000000       0.000000       0.000000  
3         0.000000       0.284688       0.000000       0.169261       0.000000  
4         0.000000       0.233134       0.000000       0.131881       0.000000  
..             ...            ...            ...            ...            ...  
127       0.000000       0.049656       0.000000       0.000000       0.000000  
128       0.000000       0.000000       0.000000       0.000000       0.000000  
129       0.000000       0.322049       0.000000       0.087975       0.000000  
130       0.000000       0.241428       0.000000       0.323920       0.000000  
131       0.309457       0.114663       0.055323       0.079820       0.269812  

[132 rows x 23328 columns]

In [51]:
normal_targets = np.zeros(len(normal_hog_features), dtype=int)
sick_targets = np.ones(len(sick_hog_features), dtype=int)

In [52]:
all_targets = np.concatenate((normal_targets, sick_targets))

In [53]:
hog_df = hog_df.assign(new_column=all_targets)

In [54]:
hog_df.head(200)

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
1     0.279231   0.014881   0.164329   0.021535   0.279231   0.232855   
2     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
3     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
4     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
..         ...        ...        ...        ...        ...        ...   
127   0.214739   0.048017   0.182212   0.000000   0.276253   0.048017   
128   0.049520   0.028470   0.005267   0.041490   0.067098   0.035962   
129   0.270254   0.000000   0.049397   0.000000   0.244503   0.000000   
130   0.243791   0.000000   0.086193   0.000000   0.060948   0.000000   
131   0.262784   0.106837   0.268913   0.000000   0.262784   0.000000   

     feature_6  feature_7  feature_8  feature_9  ...  feature_23319  \
0     0.000000   0.000000   0.000000   0.000000  ...       0.000000   
1     0.116824   0.279231   0.135777   0.070126  ...       0.193778   
2     0.000000   0.000000   0.000000   0.000000  ...       0.000000   
3     0.000000   0.000000   0.000000   0.000000  ...       0.000000   
4     0.000000   0.000000   0.000000   0.000000  ...       0.000000   
..         ...        ...        ...        ...  ...            ...   
127   0.108754   0.000000   0.276253   0.192068  ...       0.000000   
128   0.012990   0.061640   0.176685   0.261134  ...       0.000000   
129   0.049397   0.000000   0.270254   0.000000  ...       0.000000   
130   0.000000   0.000000   0.243791   0.000000  ...       0.000000   
131   0.067570   0.000000   0.262784   0.000000  ...       0.036762   

     feature_23320  feature_23321  feature_23322  feature_23323  \
0         0.000000       0.000000       0.000000       0.000000   
1         0.264742       0.145388       0.203703       0.264742   
2         0.000000       0.000000       0.000000       0.000000   
3         0.284688       0.000000       0.169261       0.000000   
4         0.299579       0.000000       0.299579       0.000000   
..             ...            ...            ...            ...   
127       0.099311       0.000000       0.070224       0.000000   
128       0.000000       0.000000       0.000000       0.000000   
129       0.322049       0.000000       0.263926       0.000000   
130       0.160952       0.000000       0.113810       0.000000   
131       0.262894       0.148428       0.127123       0.309457   

     feature_23324  feature_23325  feature_23326  feature_23327  new_column  
0         0.000000       0.000000       0.000000       0.000000           0  
1         0.080699       0.012137       0.078751       0.264742           0  
2         0.000000       0.000000       0.000000       0.000000           0  
3         0.284688       0.000000       0.169261       0.000000           0  
4         0.233134       0.000000       0.131881       0.000000           0  
..             ...            ...            ...            ...         ...  
127       0.049656       0.000000       0.000000       0.000000           1  
128       0.000000       0.000000       0.000000       0.000000           1  
129       0.322049       0.000000       0.087975       0.000000           1  
130       0.241428       0.000000       0.323920       0.000000           1  
131       0.114663       0.055323       0.079820       0.269812           1  

[132 rows x 23329 columns]